//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungTu
    {
        public int Id { get; set; }
        public string MaChungTu { get; set; }
        public string Ten { get; set; }
        public Nullable<int> MaLoaiChungTu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string NguoiKy { get; set; }
        public string MaDonVi { get; set; }
        public string DonViBanHanh { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MaVach { get; set; }
        public string FileDinhKem { get; set; }
    }
}
